#!/usr/bin/env bash

set -e

pyenv local 3.12.1

python -m venv venv
. venv/bin/activate

pip install "$(grep '^uv' < requirements_test.txt)"
uv pip install -U "pip>=21.3.1" setuptools wheel
uv pip install -r requirements_test.txt

python3 -m pytest tests

deactivate
